apiVersion: 1
groups:
    - orgId: 1
      name: error-evaluation-grp
      folder: Alerts
      interval: 10s
      rules:
        - uid: aerllu1wdszk0f
          title: Errors
          condition: C
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki_ds_main
              model:
                editorMode: code
                expr: sum by(message) (count_over_time({job="flask-app"} |~ `(?i)error` | pattern `<_> <message> duration<_>` [1m]))
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            logs: '{{ $labels.message }}'
          isPaused: false
          notification_settings:
            receiver: n8n-webhook
